/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MinerUPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
var BASE_URL = "https://mineru.net";
var MinerUClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  get headers() {
    return {
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.settings.apiToken}`
    };
  }
  async request(params) {
    const response = await (0, import_obsidian.requestUrl)(params);
    const data = response.json;
    if (data.code !== 0) {
      throw new Error(`MinerU API \u9519\u8BEF: ${data.msg || JSON.stringify(data)}`);
    }
    return data;
  }
  async batchUpload(fileNames) {
    const files = fileNames.map((name) => ({ name }));
    const data = await this.request({
      url: `${BASE_URL}/api/v4/file-urls/batch`,
      method: "POST",
      headers: this.headers,
      body: JSON.stringify({
        files,
        model_version: this.settings.modelVersion,
        is_ocr: this.settings.isOcr,
        enable_formula: this.settings.enableFormula,
        enable_table: this.settings.enableTable,
        language: this.settings.language
      })
    });
    return {
      batch_id: data.data.batch_id,
      file_urls: data.data.file_urls
    };
  }
  async uploadFile(uploadUrl, fileData) {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open("PUT", uploadUrl, true);
      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) {
          resolve();
        } else {
          reject(new Error(`\u4E0A\u4F20\u5931\u8D25: HTTP ${xhr.status} ${xhr.statusText}`));
        }
      };
      xhr.onerror = () => {
        reject(new Error("\u4E0A\u4F20\u5931\u8D25: \u7F51\u7EDC\u9519\u8BEF"));
      };
      xhr.send(fileData);
    });
  }
  async createTask(fileUrl, dataId) {
    const body = {
      url: fileUrl,
      model_version: this.settings.modelVersion,
      is_ocr: this.settings.isOcr,
      enable_formula: this.settings.enableFormula,
      enable_table: this.settings.enableTable,
      language: this.settings.language
    };
    if (dataId) {
      body.data_id = dataId;
    }
    const data = await this.request({
      url: `${BASE_URL}/api/v4/extract/task`,
      method: "POST",
      headers: this.headers,
      body: JSON.stringify(body)
    });
    return data.data.task_id;
  }
  async getTaskResult(taskId) {
    const data = await this.request({
      url: `${BASE_URL}/api/v4/extract/task/${taskId}`,
      method: "GET",
      headers: this.headers
    });
    return data.data;
  }
  async waitForTask(taskId, onProgress) {
    return new Promise((resolve, reject) => {
      const poll = async () => {
        try {
          const result = await this.getTaskResult(taskId);
          if (result.state === "done") {
            resolve(result);
            return;
          }
          if (result.state === "failed") {
            reject(new Error(`\u4EFB\u52A1\u5931\u8D25: ${result.err_msg || "\u672A\u77E5\u9519\u8BEF"}`));
            return;
          }
          if (onProgress) {
            onProgress(result);
          }
          setTimeout(poll, this.settings.pollInterval);
        } catch (err) {
          reject(err);
        }
      };
      poll();
    });
  }
  async downloadZip(zipUrl) {
    const response = await (0, import_obsidian.requestUrl)({
      url: zipUrl,
      method: "GET"
    });
    return response.arrayBuffer;
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiToken: "",
  modelVersion: "vlm",
  outputFolder: "MinerU-Output",
  enableFormula: true,
  enableTable: true,
  isOcr: false,
  language: "ch",
  pollInterval: 5e3,
  autoCreateFolder: true,
  deletePdfAfterConvert: false
};

// src/settingsTab.ts
var import_obsidian2 = require("obsidian");
var MinerUSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "MinerU PDF Converter \u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("API Token").setDesc("\u5728 mineru.net \u83B7\u53D6\u7684 API Token").addText(
      (text) => text.setPlaceholder("\u8F93\u5165\u4F60\u7684 MinerU API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6A21\u578B\u7248\u672C").setDesc("pipeline: \u9ED8\u8BA4\u6A21\u578B; vlm: \u63A8\u8350\u6A21\u578B(\u66F4\u51C6\u786E); MinerU-HTML: HTML\u6587\u4EF6\u4E13\u7528").addDropdown(
      (dropdown) => dropdown.addOption("pipeline", "pipeline (\u9ED8\u8BA4)").addOption("vlm", "vlm (\u63A8\u8350)").addOption("MinerU-HTML", "MinerU-HTML (HTML\u4E13\u7528)").setValue(this.plugin.settings.modelVersion).onChange(async (value) => {
        this.plugin.settings.modelVersion = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u8F6C\u6362\u540E\u7684 Markdown \u6587\u4EF6\u4FDD\u5B58\u5230 Vault \u4E2D\u7684\u54EA\u4E2A\u6587\u4EF6\u5939").addText(
      (text) => text.setPlaceholder("MinerU-Output").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u7528\u516C\u5F0F\u8BC6\u522B").setDesc("\u5F00\u542F\u540E\u5C06\u8BC6\u522B\u6587\u6863\u4E2D\u7684\u6570\u5B66\u516C\u5F0F").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableFormula).onChange(async (value) => {
        this.plugin.settings.enableFormula = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u7528\u8868\u683C\u8BC6\u522B").setDesc("\u5F00\u542F\u540E\u5C06\u8BC6\u522B\u6587\u6863\u4E2D\u7684\u8868\u683C").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableTable).onChange(async (value) => {
        this.plugin.settings.enableTable = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u7528 OCR").setDesc("\u5F00\u542F\u540E\u5BF9\u626B\u63CF\u4EF6\u8FDB\u884C OCR \u8BC6\u522B\uFF08\u4EC5 pipeline/vlm \u6A21\u578B\u6709\u6548\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.isOcr).onChange(async (value) => {
        this.plugin.settings.isOcr = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6587\u6863\u8BED\u8A00").setDesc("\u6587\u6863\u4E3B\u8981\u8BED\u8A00\uFF0C\u5F71\u54CD\u8BC6\u522B\u6548\u679C\u3002ch=\u4E2D\u6587, en=\u82F1\u6587").addDropdown(
      (dropdown) => dropdown.addOption("ch", "\u4E2D\u6587 (ch)").addOption("en", "\u82F1\u6587 (en)").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u8F6E\u8BE2\u95F4\u9694 (\u6BEB\u79D2)").setDesc("\u67E5\u8BE2\u4EFB\u52A1\u72B6\u6001\u7684\u95F4\u9694\u65F6\u95F4\uFF0C\u9ED8\u8BA4 5000ms").addSlider(
      (slider) => slider.setLimits(2e3, 3e4, 1e3).setValue(this.plugin.settings.pollInterval).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.pollInterval = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52A8\u521B\u5EFA\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u5982\u679C\u8F93\u51FA\u6587\u4EF6\u5939\u4E0D\u5B58\u5728\uFF0C\u81EA\u52A8\u521B\u5EFA").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoCreateFolder).onChange(async (value) => {
        this.plugin.settings.autoCreateFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u8F6C\u6362\u540E\u5220\u9664\u539F PDF").setDesc("\u8F6C\u6362\u6210\u529F\u540E\u81EA\u52A8\u5220\u9664 Vault \u4E2D\u7684\u539F PDF \u6587\u4EF6\uFF08\u8C28\u614E\u5F00\u542F\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.deletePdfAfterConvert).onChange(async (value) => {
        this.plugin.settings.deletePdfAfterConvert = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/progressModal.ts
var import_obsidian3 = require("obsidian");
var ConvertProgressModal = class extends import_obsidian3.Modal {
  constructor(app, items) {
    super(app);
    this.items = items;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("mineru-progress-modal");
    contentEl.createEl("h2", { text: "MinerU PDF \u8F6C\u6362\u8FDB\u5EA6" });
    this.containerDiv = contentEl.createDiv({ cls: "mineru-progress-list" });
    this.renderItems();
  }
  renderItems() {
    this.containerDiv.empty();
    for (const item of this.items) {
      const row = this.containerDiv.createDiv({ cls: "mineru-progress-item" });
      const nameSpan = row.createSpan({ cls: "mineru-progress-name" });
      nameSpan.setText(item.fileName);
      const statusSpan = row.createSpan({ cls: `mineru-progress-status mineru-status-${item.status}` });
      switch (item.status) {
        case "pending":
          statusSpan.setText("\u23F3 \u7B49\u5F85\u4E2D");
          break;
        case "uploading":
          statusSpan.setText("\u{1F4E4} \u4E0A\u4F20\u4E2D...");
          break;
        case "processing":
          statusSpan.setText(item.progress || "\u2699\uFE0F \u5904\u7406\u4E2D...");
          break;
        case "done":
          statusSpan.setText("\u2705 \u5B8C\u6210");
          break;
        case "failed":
          statusSpan.setText(`\u274C \u5931\u8D25: ${item.errorMsg || "\u672A\u77E5\u9519\u8BEF"}`);
          break;
      }
    }
    const allDone = this.items.every(
      (i) => i.status === "done" || i.status === "failed"
    );
    if (allDone) {
      const successCount = this.items.filter((i) => i.status === "done").length;
      const failCount = this.items.filter((i) => i.status === "failed").length;
      const summary = this.containerDiv.createDiv({ cls: "mineru-progress-summary" });
      summary.setText(`\u8F6C\u6362\u5B8C\u6210\uFF01\u6210\u529F: ${successCount}, \u5931\u8D25: ${failCount}`);
    }
  }
  updateItem(index, updates) {
    if (index >= 0 && index < this.items.length) {
      Object.assign(this.items[index], updates);
      this.renderItems();
    }
  }
  updateProgress(index, result) {
    if (result.state === "running" && result.extract_progress) {
      const { extracted_pages, total_pages } = result.extract_progress;
      this.updateItem(index, {
        status: "processing",
        progress: `\u2699\uFE0F \u5904\u7406\u4E2D (${extracted_pages}/${total_pages} \u9875)`
      });
    } else if (result.state === "converting") {
      this.updateItem(index, {
        status: "processing",
        progress: "\u2699\uFE0F \u683C\u5F0F\u8F6C\u6362\u4E2D..."
      });
    }
  }
  markDone(index) {
    this.updateItem(index, { status: "done" });
  }
  markFailed(index, errorMsg) {
    this.updateItem(index, { status: "failed", errorMsg });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    if (this.onCloseCallback) {
      this.onCloseCallback();
    }
  }
  setOnClose(cb) {
    this.onCloseCallback = cb;
  }
};

// src/pdfSelectModal.ts
var import_obsidian4 = require("obsidian");
var PdfSelectModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.selectedFiles = /* @__PURE__ */ new Set();
    this.onChoose = onChoose;
    this.setPlaceholder("\u641C\u7D22\u5E76\u9009\u62E9 PDF \u6587\u4EF6...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "\u5BFC\u822A" },
      { command: "\u21B5", purpose: "\u5207\u6362\u9009\u4E2D" },
      { command: "esc", purpose: "\u53D6\u6D88" }
    ]);
  }
  getItems() {
    return this.app.vault.getFiles().filter((f) => f.extension === "pdf");
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item, evt) {
    if (this.selectedFiles.has(item)) {
      this.selectedFiles.delete(item);
    } else {
      this.selectedFiles.add(item);
    }
    this.updateConfirmButton();
  }
  onOpen() {
    super.onOpen();
    const footer = this.modalEl.createDiv({ cls: "mineru-pdf-select-footer" });
    this.confirmBtn = footer.createEl("button", {
      text: "\u786E\u8BA4\u8F6C\u6362 (0)",
      cls: "mod-cta"
    });
    this.confirmBtn.addEventListener("click", () => {
      this.onChoose(Array.from(this.selectedFiles));
      this.close();
    });
    const selectAllBtn = footer.createEl("button", { text: "\u5168\u9009" });
    selectAllBtn.addEventListener("click", () => {
      this.selectedFiles = new Set(this.getItems());
      this.updateConfirmButton();
    });
    const clearBtn = footer.createEl("button", { text: "\u6E05\u7A7A" });
    clearBtn.addEventListener("click", () => {
      this.selectedFiles.clear();
      this.updateConfirmButton();
    });
  }
  updateConfirmButton() {
    if (this.confirmBtn) {
      this.confirmBtn.setText(`\u786E\u8BA4\u8F6C\u6362 (${this.selectedFiles.size})`);
    }
  }
};

// main.ts
var MinerUPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.client = new MinerUClient(this.settings);
    this.addCommand({
      id: "mineru-convert-selected-pdf",
      name: "\u8F6C\u6362\u9009\u4E2D\u7684 PDF \u6587\u4EF6",
      callback: () => this.convertSelectedPdfs()
    });
    this.addCommand({
      id: "mineru-convert-all-pdfs",
      name: "\u8F6C\u6362 Vault \u4E2D\u6240\u6709 PDF",
      callback: () => this.convertAllPdfs()
    });
    this.addCommand({
      id: "mineru-convert-current-folder",
      name: "\u8F6C\u6362\u5F53\u524D\u6587\u4EF6\u5939\u4E2D\u7684 PDF",
      callback: () => this.convertCurrentFolderPdfs()
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "pdf") {
          menu.addItem((item) => {
            item.setTitle("MinerU: \u8F6C\u6362\u4E3A Markdown").setIcon("file-text").onClick(() => this.convertFiles([file]));
          });
        }
        if (file instanceof import_obsidian5.TFolder) {
          menu.addItem((item) => {
            item.setTitle("MinerU: \u8F6C\u6362\u6587\u4EF6\u5939\u4E2D\u7684 PDF").setIcon("folder").onClick(() => this.convertFolderPdfs(file));
          });
        }
      })
    );
    this.addSettingTab(new MinerUSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.client = new MinerUClient(this.settings);
  }
  validateToken() {
    if (!this.settings.apiToken) {
      new import_obsidian5.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 MinerU API Token");
      return false;
    }
    return true;
  }
  async ensureOutputFolder() {
    const folderPath = this.settings.outputFolder;
    const existing = this.app.vault.getAbstractFileByPath(folderPath);
    if (existing instanceof import_obsidian5.TFolder) {
      return existing;
    }
    if (this.settings.autoCreateFolder) {
      await this.app.vault.createFolder(folderPath);
      const created = this.app.vault.getAbstractFileByPath(folderPath);
      return created instanceof import_obsidian5.TFolder ? created : null;
    }
    new import_obsidian5.Notice(`\u8F93\u51FA\u6587\u4EF6\u5939 "${folderPath}" \u4E0D\u5B58\u5728\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u5F00\u542F\u81EA\u52A8\u521B\u5EFA\u6216\u624B\u52A8\u521B\u5EFA`);
    return null;
  }
  async convertSelectedPdfs() {
    if (!this.validateToken())
      return;
    const modal = new PdfSelectModal(this.app, (files) => {
      this.convertFiles(files);
    });
    modal.open();
  }
  async convertAllPdfs() {
    if (!this.validateToken())
      return;
    const pdfFiles = this.app.vault.getFiles().filter((f) => f.extension === "pdf");
    if (pdfFiles.length === 0) {
      new import_obsidian5.Notice("Vault \u4E2D\u6CA1\u6709 PDF \u6587\u4EF6");
      return;
    }
    this.convertFiles(pdfFiles);
  }
  async convertCurrentFolderPdfs() {
    if (!this.validateToken())
      return;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian5.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6\u4EE5\u786E\u5B9A\u5F53\u524D\u6587\u4EF6\u5939");
      return;
    }
    const parentFolder = activeFile.parent;
    if (!parentFolder)
      return;
    this.convertFolderPdfs(parentFolder);
  }
  async convertFolderPdfs(folder) {
    if (!this.validateToken())
      return;
    const pdfFiles = folder.children.filter((f) => f instanceof import_obsidian5.TFile && f.extension === "pdf");
    if (pdfFiles.length === 0) {
      new import_obsidian5.Notice(`\u6587\u4EF6\u5939 "${folder.path}" \u4E2D\u6CA1\u6709 PDF \u6587\u4EF6`);
      return;
    }
    this.convertFiles(pdfFiles);
  }
  async convertFiles(pdfFiles) {
    if (pdfFiles.length === 0) {
      new import_obsidian5.Notice("\u6CA1\u6709\u9009\u62E9 PDF \u6587\u4EF6");
      return;
    }
    const outputFolder = await this.ensureOutputFolder();
    if (!outputFolder)
      return;
    const items = pdfFiles.map((f) => ({
      fileName: f.name,
      file: f,
      status: "pending",
      progress: "",
      errorMsg: ""
    }));
    const progressItems = items.map((i) => ({
      fileName: i.fileName,
      status: "pending"
    }));
    const modal = new ConvertProgressModal(this.app, progressItems);
    modal.open();
    new import_obsidian5.Notice(`\u5F00\u59CB\u8F6C\u6362 ${pdfFiles.length} \u4E2A PDF \u6587\u4EF6...`);
    const BATCH_SIZE = 50;
    for (let batchStart = 0; batchStart < items.length; batchStart += BATCH_SIZE) {
      const batch = items.slice(batchStart, batchStart + BATCH_SIZE);
      const batchIndices = batch.map((_, i) => batchStart + i);
      try {
        for (let i = 0; i < batch.length; i++) {
          modal.updateItem(batchIndices[i], { status: "uploading" });
        }
        const fileNames = batch.map((item) => item.fileName);
        const uploadResult = await this.client.batchUpload(fileNames);
        for (let i = 0; i < batch.length; i++) {
          const item = batch[i];
          const uploadUrl = uploadResult.file_urls[i];
          try {
            const fileData = await this.app.vault.readBinary(item.file);
            await this.client.uploadFile(uploadUrl, fileData);
          } catch (err) {
            modal.markFailed(
              batchIndices[i],
              `\u4E0A\u4F20\u5931\u8D25: ${err.message}`
            );
            batch[i] = null;
          }
        }
        const validItems = batch.filter((item) => item !== null);
        const validIndices = batchIndices.filter(
          (_, i) => batch[i] !== null
        );
        const taskPromises = validItems.map(async (item, i) => {
          const globalIndex = validIndices[i];
          const uploadUrl = uploadResult.file_urls[validIndices[i] - batchStart];
          try {
            const taskId = await this.client.createTask(uploadUrl);
            return { taskId, item, globalIndex };
          } catch (err) {
            modal.markFailed(globalIndex, `\u521B\u5EFA\u4EFB\u52A1\u5931\u8D25: ${err.message}`);
            return null;
          }
        });
        const taskResults = await Promise.all(taskPromises);
        const validTasks = taskResults.filter((t) => t !== null);
        const pollPromises = validTasks.map(({ taskId, item, globalIndex }) => {
          modal.updateItem(globalIndex, {
            status: "processing",
            progress: "\u2699\uFE0F \u7B49\u5F85\u5904\u7406..."
          });
          return new Promise(async (resolve) => {
            try {
              const maxWaitTime = 10 * 60 * 1e3;
              const startTime = Date.now();
              const poll = async () => {
                if (Date.now() - startTime > maxWaitTime) {
                  modal.markFailed(globalIndex, "\u8D85\u65F6\uFF0810\u5206\u949F\uFF09");
                  resolve();
                  return;
                }
                try {
                  const taskResult = await this.client.getTaskResult(taskId);
                  if (taskResult.state === "done" && taskResult.full_zip_url) {
                    await this.downloadAndSave(
                      taskResult.full_zip_url,
                      item.fileName,
                      outputFolder
                    );
                    modal.markDone(globalIndex);
                    if (this.settings.deletePdfAfterConvert) {
                      await this.app.vault.delete(item.file);
                    }
                    resolve();
                    return;
                  }
                  if (taskResult.state === "failed") {
                    modal.markFailed(
                      globalIndex,
                      taskResult.err_msg || "\u5904\u7406\u5931\u8D25"
                    );
                    resolve();
                    return;
                  }
                  modal.updateProgress(globalIndex, taskResult);
                  setTimeout(poll, this.settings.pollInterval);
                } catch (err) {
                  modal.markFailed(globalIndex, err.message);
                  resolve();
                }
              };
              poll();
            } catch (err) {
              modal.markFailed(globalIndex, err.message);
              resolve();
            }
          });
        });
        await Promise.all(pollPromises);
      } catch (err) {
        for (const idx of batchIndices) {
          modal.markFailed(idx, `\u6279\u91CF\u64CD\u4F5C\u5931\u8D25: ${err.message}`);
        }
      }
    }
    const successCount = progressItems.filter(
      (i) => i.status === "done"
    ).length;
    new import_obsidian5.Notice(`\u8F6C\u6362\u5B8C\u6210\uFF01\u6210\u529F ${successCount}/${pdfFiles.length}`);
  }
  async downloadAndSave(zipUrl, originalFileName, outputFolder) {
    const zipData = await this.client.downloadZip(zipUrl);
    const mdContent = await this.extractMdFromZip(zipData);
    if (!mdContent) {
      throw new Error("ZIP \u4E2D\u672A\u627E\u5230 Markdown \u6587\u4EF6");
    }
    const baseName = originalFileName.replace(/\.pdf$/i, "");
    const mdFileName = `${baseName}.md`;
    const mdFilePath = `${outputFolder.path}/${mdFileName}`;
    const existing = this.app.vault.getAbstractFileByPath(mdFilePath);
    if (existing instanceof import_obsidian5.TFile) {
      await this.app.vault.modify(existing, mdContent);
    } else {
      await this.app.vault.create(mdFilePath, mdContent);
    }
  }
  async extractMdFromZip(zipData) {
    try {
      const JSZip = await this.loadJSZip();
      const zip = await JSZip.loadAsync(zipData);
      let mdContent = null;
      const files = Object.keys(zip.files);
      const mdFile = files.find(
        (f) => f.endsWith("full.md") || f.endsWith(".md")
      );
      if (mdFile) {
        mdContent = await zip.files[mdFile].async("string");
      }
      return mdContent;
    } catch (err) {
      console.error("\u89E3\u538B ZIP \u5931\u8D25:", err);
      throw new Error(`\u89E3\u538B\u5931\u8D25: ${err.message}`);
    }
  }
  async loadJSZip() {
    if (window.JSZip) {
      return window.JSZip;
    }
    return new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js";
      script.onload = () => {
        if (window.JSZip) {
          resolve(window.JSZip);
        } else {
          reject(new Error("JSZip \u52A0\u8F7D\u5931\u8D25"));
        }
      };
      script.onerror = () => reject(new Error("JSZip \u811A\u672C\u52A0\u8F7D\u5931\u8D25"));
      document.head.appendChild(script);
    });
  }
};
